"""
Strategy & MVP Domain Models (Part 2)

Pydantic data schemas for HMW Opportunities, RICE Evaluation items,
AI Assistant Recommendations, Cart Contexts, Telemetry Events, and Experiment Metrics.
"""

from typing import Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from datetime import datetime, timezone


class HMWOpportunity(BaseModel):
    """How Might We (HMW) Opportunity Frame derived from Behavior Graph friction nodes."""
    hmw_id: str
    friction_node_id: str
    opportunity_area: str
    hmw_statement: str
    target_archetype: str
    underlying_friction: str
    potential_impact_level: str = "high"  # high | medium | low
    created_at: Optional[str] = None

    @field_validator("hmw_statement")
    @classmethod
    def validate_hmw_prefix(cls, v: str) -> str:
        if not v.strip().lower().startswith("how might we"):
            return f"How might we {v.strip()}"
        return v


class RICEEvaluationItem(BaseModel):
    """RICE Prioritization Matrix item with mathematical score computation."""
    solution_id: str
    title: str
    description: str
    reach: int = Field(default=800000, ge=0, description="Monthly Active Users reached or scale 1-10")
    impact: float = Field(default=4.0, ge=0.1, le=10.0, description="Impact score")
    confidence: float = Field(default=0.85, ge=0.01, le=10.0, description="Confidence score")
    effort: float = Field(default=3.0, ge=0.1, description="Effort required")
    reach_scale: Optional[float] = None
    impact_scale: Optional[float] = None
    confidence_scale: Optional[float] = None
    effort_scale: Optional[float] = None
    rice_score: float = 0.0
    rank: Optional[int] = None
    is_selected_mvp: bool = False
    justification: str = ""
    pain_point: Optional[str] = None
    what_it_solves: Optional[str] = None
    trade_off_pros: Optional[str] = None
    trade_off_limitations: Optional[str] = None
    why_this_solution: Optional[str] = None

    def calculate_rice(self) -> float:
        """Computes RICE score: (Reach * Impact * Confidence) / Effort."""
        if self.reach_scale is not None and self.impact_scale is not None and self.confidence_scale is not None and self.effort_scale is not None:
            safe_effort = max(0.5, self.effort_scale)
            score = (self.reach_scale * self.impact_scale * self.confidence_scale) / safe_effort
        else:
            safe_effort = max(0.5, self.effort)
            score = (self.reach * self.impact * self.confidence) / safe_effort
        self.rice_score = round(score, 2)
        return self.rice_score


class RICESensitivityTrigger(BaseModel):
    """Trigger explaining conditions under which RICE rankings shift."""
    trigger_id: str
    strategic_trigger: str
    ranking_shift: str
    reasoning: str



class AssistantRecommendationCard(BaseModel):
    """Dynamic recommendation card generated by the AI Category Assistant."""
    recommendation_id: str
    category_name: str
    suggested_sku: str
    nudge_text: str
    trial_incentive: str = "100% Risk-Free Trial"
    social_proof_badge: str = "Popular Non-Grocery Addition"
    price_inr: float
    discounted_price_inr: Optional[float] = None
    in_stock: bool = True
    confidence_score: float = 0.90


class AssistantCartContext(BaseModel):
    """Current user cart state passed to the AI Category Assistant."""
    user_id: Optional[str] = "anon_user"
    cart_items: List[str] = Field(default_factory=list)
    primary_category: Optional[str] = "Groceries"
    dark_store_id: Optional[str] = "ds_indiranagar_01"
    dismiss_count: int = 0


class AssistantRecommendationResponse(BaseModel):
    """Response payload returned by the AI Category Assistant recommendation engine."""
    session_id: str
    cart_context: AssistantCartContext
    recommendations: List[AssistantRecommendationCard] = Field(default_factory=list)
    suppress_widget: bool = False
    suppress_reason: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class MVPTelemetryEvent(BaseModel):
    """Telemetry logging event for the AI Assistant MVP feature."""
    event_id: str
    session_id: str
    user_id: Optional[str] = "anon_user"
    event_type: str  # widget_impression | card_click | item_added_to_cart | nudge_dismissed | category_checkout_converted
    recommendation_id: Optional[str] = None
    target_category: Optional[str] = None
    variant: str = "variant_ai_assistant"  # control | variant_ai_assistant
    metadata: Dict = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class MVPExperimentMetrics(BaseModel):
    """Telemetry metrics dashboard for A/B testing and North Star tracking."""
    experiment_id: str = "exp_category_discovery_v1"
    total_active_users: int = 0
    control_users: int = 0
    variant_users: int = 0
    north_star_mac_cross_category_pct: float = 24.8  # Target > 28.0%
    cross_category_conversion_rate_pct: float = 14.2
    basket_size_expansion_inr: float = 118.5
    guardrail_cart_abandonment_pct: float = 1.8  # Must stay <= 2.0%
    guardrail_delivery_sla_compliance_pct: float = 98.4  # Must stay >= 98.0%
    guardrail_nudge_opt_out_pct: float = 1.2  # Must stay <= 1.5%
    statistically_significant: bool = False
    confidence_level_pct: float = 95.0
